---
version: "3"
services:
  xteve:
    hostname: "xteve"
    container_name: "xteve"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "alturismo/xteve"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/xteve/:/root/.xteve:rw"
      - "${APPFOLDER}/xteve/_config:/config:rw"
      - "${APPFOLDER}/xteve/temp/:/tmp/xteve:rw"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.xteve-rtr.entrypoints=https"
      - "traefik.http.routers.xteve-rtr.rule=Host(`xteve.${DOMAIN}`)"
      - "traefik.http.routers.xteve-rtr.tls=true"
      - "traefik.http.routers.xteve-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.xteve-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.xteve-rtr.service=xteve-svc"
      - "traefik.http.services.xteve-svc.loadbalancer.server.port=34400"
networks:
  proxy:
    driver: bridge
    external: true
